-- PASS 43 · P2 — THE AFTER SNAPSHOT, keyed to the two uids the device
-- reported and to nothing else. READ ONLY: one statement, one `select`,
-- every other line a `union all select`. Counts, UUIDs, states and
-- timestamps only.
--   SOURCE A (anonymous, pre-tap)  F5A425DE-E10B-456B-8FDE-9D488D234929
--   DEST   B (permanent, post-tap) 280CAA8E-B635-49B7-8BF1-CA725F71798A
with a as (select 'F5A425DE-E10B-456B-8FDE-9D488D234929'::uuid as id),
     b as (select '280CAA8E-B635-49B7-8BF1-CA725F71798A'::uuid as id)
select 'A_auth_users_row'      as k, (select count(*)::text from auth.users u, a where u.id = a.id) as v
union all select 'A_identities',        (select count(*)::text from auth.identities i, a where i.user_id = a.id)
union all select 'A_owns_users',        (select count(*)::text from public.users t, a where t.id = a.id)
union all select 'A_owns_weight',       (select count(*)::text from public.weight_logs t, a where t.user_id = a.id)
union all select 'A_owns_food',         (select count(*)::text from public.food_logs t, a where t.user_id = a.id)
union all select 'A_owns_sessions',     (select count(*)::text from public.session_logs t, a where t.user_id = a.id)
union all select 'A_owns_checks',       (select count(*)::text from public.program_day_checks t, a where t.user_id = a.id)
union all select 'A_owns_plans',        (select count(*)::text from public.program_plans t, a where t.user_id = a.id)
union all select 'A_owns_dayprogress',  (select count(*)::text from public.day_progress t, a where t.user_id = a.id)
union all select 'A_owns_reflections',  (select count(*)::text from public.day_reflections t, a where t.user_id = a.id)
union all select 'A_owns_observations', (select count(*)::text from public.observations t, a where t.user_id = a.id)
union all select 'A_owns_doses',        (select count(*)::text from public.dose_events t, a where t.user_id = a.id)
union all select 'A_owns_regimens',     (select count(*)::text from public.regimen_plans t, a where t.user_id = a.id)
union all select 'A_owns_consent',      (select count(*)::text from public.consent_grants t, a where t.user_id = a.id)
union all select 'A_owns_coachmsgs',    (select count(*)::text from public.coach_messages t, a where t.user_id = a.id)
-- the destination
union all select 'B_auth_users_row',    (select count(*)::text from auth.users u, b where u.id = b.id)
union all select 'B_is_anonymous',      (select u.is_anonymous::text from auth.users u, b where u.id = b.id)
union all select 'B_created_at',        (select u.created_at::text from auth.users u, b where u.id = b.id)
union all select 'B_identity_providers',(select string_agg(i.provider, '+' order by i.provider) from auth.identities i, b where i.user_id = b.id)
union all select 'B_identity_count',    (select count(*)::text from auth.identities i, b where i.user_id = b.id)
union all select 'B_apple_identity_created', (select max(i.created_at)::text from auth.identities i, b where i.user_id = b.id and i.provider='apple')
union all select 'B_owns_users',        (select count(*)::text from public.users t, b where t.id = b.id)
union all select 'B_owns_weight',       (select count(*)::text from public.weight_logs t, b where t.user_id = b.id)
union all select 'B_owns_weight_today_after_0500', (select count(*)::text from public.weight_logs t, b where t.user_id = b.id and t.created_at >= '2026-08-15 05:00:00+00')
union all select 'B_owns_food',         (select count(*)::text from public.food_logs t, b where t.user_id = b.id)
union all select 'B_owns_food_after_0500', (select count(*)::text from public.food_logs t, b where t.user_id = b.id and t.created_at >= '2026-08-15 05:00:00+00')
union all select 'B_owns_sessions',     (select count(*)::text from public.session_logs t, b where t.user_id = b.id)
union all select 'B_owns_checks',       (select count(*)::text from public.program_day_checks t, b where t.user_id = b.id)
union all select 'B_owns_plans',        (select count(*)::text from public.program_plans t, b where t.user_id = b.id)
union all select 'B_plan_phases',       (select string_agg(t.phase || '@' || t.created_at::date::text, ' | ' order by t.created_at) from public.program_plans t, b where t.user_id = b.id)
union all select 'B_owns_dayprogress',  (select count(*)::text from public.day_progress t, b where t.user_id = b.id)
union all select 'B_owns_reflections',  (select count(*)::text from public.day_reflections t, b where t.user_id = b.id)
union all select 'B_owns_observations', (select count(*)::text from public.observations t, b where t.user_id = b.id)
union all select 'B_owns_doses',        (select count(*)::text from public.dose_events t, b where t.user_id = b.id)
union all select 'B_owns_regimens',     (select count(*)::text from public.regimen_plans t, b where t.user_id = b.id)
union all select 'B_owns_consent',      (select count(*)::text from public.consent_grants t, b where t.user_id = b.id)
union all select 'B_owns_coachmsgs',    (select count(*)::text from public.coach_messages t, b where t.user_id = b.id)
-- the receipt
union all select 'H_total',             (select count(*)::text from public.account_handoffs)
union all select 'H_open',              (select count(*) filter (where state='open')::text from public.account_handoffs)
union all select 'H_completed',         (select count(*) filter (where state='completed')::text from public.account_handoffs)
union all select 'H_row', (select h.state || ' | src=' || coalesce(h.source_user_id::text,'NULL')
                                  || ' | dst=' || coalesce(h.destination_user_id::text,'NULL')
                                  || ' | digest=' || coalesce(h.subject_hash,'NULL')
                                  || ' | provider=' || h.provider
                                  || ' | created=' || h.created_at::text
                                  || ' | completed=' || coalesce(h.completed_at::text,'NULL')
                                  || ' | retired=' || coalesce(h.source_retired_at::text,'NULL')
                             from public.account_handoffs h order by h.created_at desc limit 1)
union all select 'H_dst_is_B',          (select (h.destination_user_id = b.id)::text from public.account_handoffs h, b order by h.created_at desc limit 1)
-- global drift vs the BEFORE snapshot (T0 = 2026-08-15 05:26:45Z)
union all select 'auth_users_total',        (select count(*)::text from auth.users)
union all select 'auth_users_anonymous',    (select count(*) filter (where is_anonymous)::text from auth.users)
union all select 'auth_users_permanent',    (select count(*) filter (where not is_anonymous)::text from auth.users)
union all select 'auth_users_since_T0',     (select count(*)::text from auth.users where created_at >= '2026-08-15 05:26:45+00')
union all select 'identities_apple',        (select count(*)::text from auth.identities where provider='apple')
union all select 'identities_apple_since_T0',(select count(*)::text from auth.identities where provider='apple' and created_at >= '2026-08-15 05:26:45+00')
union all select 'users_profile_rows',      (select count(*)::text from public.users)
union all select 'weight_logs',             (select count(*)::text from public.weight_logs)
union all select 'food_logs',               (select count(*)::text from public.food_logs)
union all select 'session_logs',            (select count(*)::text from public.session_logs)
union all select 'program_plans',           (select count(*)::text from public.program_plans)
union all select 'program_day_checks',      (select count(*)::text from public.program_day_checks)
union all select 'day_progress',            (select count(*)::text from public.day_progress)
union all select 'day_reflections',         (select count(*)::text from public.day_reflections)
union all select 'observations',            (select count(*)::text from public.observations)
union all select 'dose_events',             (select count(*)::text from public.dose_events)
union all select 'regimen_plans',           (select count(*)::text from public.regimen_plans)
union all select 'consent_grants',          (select count(*)::text from public.consent_grants)
union all select 'care_relationships',      (select count(*)::text from public.care_relationships)
union all select 'coach_messages',          (select count(*)::text from public.coach_messages)
union all select 'storage_objects',         (select count(*)::text from storage.objects)
;
